ReplicaNumber: 3

containers:
  containerPort: 8080
  image: 'quay.io/sbahar/workshop-lab'
  tag: 'chart_v1'

service:
  servicePort: 8080

probes:
  readiness:
    httpGet:
      path: /health/readiness
    timeout:
      initialDelaySeconds: 1
      timeoutSeconds: 1
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
  liveness:
    httpGet:
      path: /health/liveliness
    timeout:
      initialDelaySeconds: 1
      timeoutSeconds: 1
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3

volume:
  mount:
    path: /tmp/html

argocd:
  syncwave:
     deployment: 5

